// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Float: typeof import('headlessui-float-vue')['Float']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    PlayerControlButton: typeof import('./src/components/PlayerControlButton.vue')['default']
    PlayerControls: typeof import('./src/components/PlayerControls.vue')['default']
    PlayerProgressBar: typeof import('./src/components/PlayerProgressBar.vue')['default']
    PlayerTime: typeof import('./src/components/PlayerTime.vue')['default']
    PlayerVolume: typeof import('./src/components/PlayerVolume.vue')['default']
    Playlist: typeof import('./src/components/Playlist.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}

export { }
