// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/IconTooling.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

export { }
