// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Float: typeof import('@headlessui-float/vue')['Float']
    Layout: typeof import('./../components/Layout.vue')['default']
    Player: typeof import('./../components/Player.vue')['default']
    PlayerControlButton: typeof import('./../components/PlayerControlButton.vue')['default']
    PlayerControls: typeof import('./../components/PlayerControls.vue')['default']
    PlayerProgressBar: typeof import('./../components/PlayerProgressBar.vue')['default']
    PlayerTime: typeof import('./../components/PlayerTime.vue')['default']
    PlayerVolume: typeof import('./../components/PlayerVolume.vue')['default']
    Playlist: typeof import('./../components/Playlist.vue')['default']
    ProgressBar: typeof import('./../components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search.vue')['default']
  }
}
